;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
e.=explorer .
gl=git log --oneline --all --graph --decorate  $*
ls=ls --show-control-chars -F --color $*
pwd=cd
clear=cls
history=cat "%CMDER_ROOT%\config\.history"
unalias=alias /d $1
vi=vim $*
cmderr=cd /d "%CMDER_ROOT%"
;= do not use none-ascii character
cc=c:
~=c: && cd c:\Users\dell\
adminlte=start chrome "http://localhost:9720/pages/UI/icons.html" && http-server -p 9720 "C:\pacofuture\AdminLTE"
ccroot=c: && cd c:\
cleanpipenv=pipenv --rm && rm -f Pipfile Pipfile.log
dd=d:
ddroot=d: && cd d:\
edit=start notepad++ $1
reloadshell=alias/reload
editshell=start notepad++ c:\Users\dell\Downloads\config\user-aliases.cmd
importshell=cat c:\personal_project\fee\win-sh-script\user_aliases.cmd > c:\Users\dell\cmder_mini\config\user_aliases.cmd; alias/reload
exportshell=cat c:\Users\dell\cmder_mini\config\user_aliases.cmd > c:\personal_project\fee\win-sh-script\user_aliases.cmd
home=c: && cd c:\Users\dell\
hosts=start notepad++ c:\Windows\System32\drivers\etc\hosts
ll=ls -al
open=start
pacofuture=c: && cd c:\pacofuture\
personal=c: && cd c:\personal_project\
rmpipenv=pipenv --rm && rm -f Pipfile Pipfile.lock
server=http-server
serverhere=http-server -c-1
vm=ssh ho@vm
newpipenv=bash -c 'if [ -e "/c/Python/$1/python.exe" ]; then pipenv --python "C:/Python/$1/python.exe"; sed -i "s/pypi.org\/simple/mirrors.aliyun.com\/pypi\/simple\//g" Pipfile; if [ -e "requirements.txt" ]; then echo "detect requirements.txt installing..."; pipenv install -r requirements.txt; fi; cat Pipfile; pipenv graph; pipenv run Python -V; else echo "version $1 not found,download: https://npm.taobao.org/mirrors/python/$1/"; fi'
