version: '3'

services:
  pyweb:
    build: ./app
    # ports:
    #   - "127.0.0.1:8701:8888"
    env_file:
        - ./mysql/secret.env
    environment:
      - MYSQL_HOST=mysqldemo
      - MYSQL_PORT=3306
      - MONGO_HOST=mongodemo
      - MONGO_PORT=27017
    depends_on:
      - mysqldemo
      - mongodemo
      - redisdemo
    volumes:
      - ./app:/app:ro
    working_dir: /app
    command: ["./wait-for-it", "mysqldemo:3306", "--", "./wait-for-it", "mongodemo:27017", "--", "./wait-for-it", "redisdemo:6379", "--", "python2", "app.py"]

  mysqldemo:
    image: mysql:5.7
    env_file:
        - ./mysql/secret.env
    command:
        --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
        - mysql_vol:/var/lib/mysql
    restart: unless-stopped

  # php-admin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   env_file:
  #       - ./mysql/secret.env
  #   links:
  #       - mysqldemo:db
  #   depends_on:
  #       - mysqldemo
  #   restart: unless-stopped

  mongodemo:
    image: mongo:3.6-stretch
    env_file:
        - ./mysql/secret.env
    volumes:
        - mongo_vol:/data/db
    restart: unless-stopped
    command: ["mongod", "--smallfiles"]

  mongo-express:
    image: mongo-express:0.49
    env_file:
        - ./mongo/secret.env
    links:
        - mongodemo:mongo
    depends_on:
        - mongodemo
    restart: unless-stopped

  nignx-demo:
    image: nginx:stable-alpine
    volumes:
        - ./app/static:/ngx-static:ro
        - ./nginx/app.conf:/etc/nginx/conf.d/app.conf:ro
    links:
        - pyweb
        - mongo-express
        - redis-admin
        - adminer
        # - php-admin
    ports:
        - 0.0.0.0:9981:80
    restart: unless-stopped

  redisdemo:
    image: redis:4.0.11-alpine3.8
    volumes:
        - redis_vol:/data
    restart: unless-stopped

  redis-admin:
    image: erikdubbelboer/phpredisadmin:v1.11.0
    env_file:
        - ./redis/secret.env
    environment:
        - REDIS_1_HOST=redisdemo
        - REDIS_1_PORT=6379
    depends_on:
        - redisdemo
    restart: unless-stopped

  adminer:
    image: adminer:4.7.0-standalone
    env_file:
        - ./mysql/secret.env
    links:
        - mysqldemo:db
    depends_on:
        - mysqldemo
    restart: unless-stopped

volumes:
  mysql_vol:
  mongo_vol:
  redis_vol:
