version: '3'

services:
    # docker run -it --rm \
    #    --env-file=./app/secret.env \
    #    --env-file=./postgres/secret.env \
    #    --network=sentry_sentry_network \
    #    -e SENTRY_REDIS_HOST=redis \
    #    -e SENTRY_POSTGRES_HOST=postgres \
    #    sentry:latest upgrade

    # docker run -it --rm \
    #    --env-file=./app/secret.env \
    #    --env-file=./postgres/secret.env \
    #    --network=sentry_sentry_network \
    #    -e SENTRY_REDIS_HOST=redis \
    #    -e SENTRY_POSTGRES_HOST=postgres \
    #    -p 9991:9000 \
    #    sentry:latest

    redis:
        image: redis:4.0.11-alpine3.8
        networks:
            - sentry_network
        volumes:
            - sentry_redis_vol:/data
        restart: unless-stopped

    postgres:
        image: postgres:latest
        env_file:
            - ./postgres/secret.env
        networks:
            - sentry_network
        volumes:
            - sentry_postgres_vol:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    sentry_postgres_vol:
    sentry_redis_vol:

networks:
    sentry_network:
